// ASSIGNMENT ON STORED FUNCTIONS 


DELIMITER @@

CREATE FUNCTION Mark_grade(mrk int)
RETURNS varchar(15)
DETERMINISTIC
READS SQL DATA
BEGIN
    IF mrk>80 THEN
		RETURN 'Outstanding';
	ELSEIF mrk BETWEEN 70 AND 80 THEN 
		RETURN 'Excellent';
	ELSEIF mrk BETWEEN 60 AND 70 THEN 
		RETURN 'Good';
	ELSEIF mrk BETWEEN 50 AND 60 THEN
		RETURN 'Average';
	END IF;
    
END @@

DELIMITER ;

// CHECKING QUERY
SELECT Mark_grade(88);
